from __future__ import annotations

import uuid
from typing import Protocol

from ytforge.domain.entities import Channel, ChannelMember


class ChannelRepository(Protocol):
    async def get_by_id(self, channel_id: uuid.UUID) -> Channel | None: ...
    async def add(self, channel: Channel) -> None: ...
    async def update(self, channel: Channel) -> None: ...
    async def list_for_user(self, user_id: uuid.UUID) -> list[Channel]: ...


class ChannelMemberRepository(Protocol):
    async def get(self, channel_id: uuid.UUID, user_id: uuid.UUID) -> ChannelMember | None: ...
    async def add(self, member: ChannelMember) -> None: ...
    async def update(self, member: ChannelMember) -> None: ...
    async def list_for_channel(self, channel_id: uuid.UUID) -> list[ChannelMember]: ...
