from __future__ import annotations

import uuid
from decimal import Decimal
from typing import Protocol

from ytforge.application.common.pagination import Page, PageParams
from ytforge.domain.entities import PromptRun, PromptTemplate, PromptVersion


class PromptTemplateRepository(Protocol):
    async def get_by_id(self, template_id: uuid.UUID) -> PromptTemplate | None: ...
    async def get_by_agent_and_name(self, agent: str, name: str) -> PromptTemplate | None: ...
    async def add(self, template: PromptTemplate) -> None: ...
    async def list_all(self) -> list[PromptTemplate]: ...


class PromptVersionRepository(Protocol):
    async def add(self, version: PromptVersion) -> None: ...
    async def get_latest(self, template_id: uuid.UUID) -> PromptVersion | None: ...
    async def list_for_template(self, template_id: uuid.UUID) -> list[PromptVersion]: ...


class PromptRunRepository(Protocol):
    async def add(self, run: PromptRun) -> None: ...
    async def list_for_version(
        self, prompt_version_id: uuid.UUID, params: PageParams
    ) -> Page[PromptRun]: ...
    async def sum_cost_for_project(self, project_id: uuid.UUID) -> Decimal: ...
