from __future__ import annotations

import uuid
from typing import Protocol

from ytforge.application.common.pagination import Page, PageParams
from ytforge.domain.entities import Script


class ScriptRepository(Protocol):
    async def get_by_id(self, script_id: uuid.UUID) -> Script | None: ...
    async def add(self, script: Script) -> None: ...
    async def update(self, script: Script) -> None: ...
    async def get_latest_for_project(self, project_id: uuid.UUID) -> Script | None: ...
    async def list_for_project(self, project_id: uuid.UUID, params: PageParams) -> Page[Script]: ...
