from __future__ import annotations

import uuid
from typing import Protocol

from ytforge.domain.entities import Scene, Storyboard


class StoryboardRepository(Protocol):
    async def get_by_id(self, storyboard_id: uuid.UUID) -> Storyboard | None: ...
    async def get_by_project(self, project_id: uuid.UUID) -> Storyboard | None: ...
    async def add(self, storyboard: Storyboard) -> None: ...
    async def update(self, storyboard: Storyboard) -> None: ...


class SceneRepository(Protocol):
    async def get_by_id(self, scene_id: uuid.UUID) -> Scene | None: ...
    async def add(self, scene: Scene) -> None: ...
    async def update(self, scene: Scene) -> None: ...
    async def list_for_storyboard(self, storyboard_id: uuid.UUID) -> list[Scene]: ...
