from __future__ import annotations

import uuid
from typing import Protocol

from ytforge.application.common.pagination import Page, PageParams
from ytforge.domain.entities import SeoMetadata, Video


class VideoRepository(Protocol):
    async def get_by_id(self, video_id: uuid.UUID) -> Video | None: ...
    async def add(self, video: Video) -> None: ...
    async def update(self, video: Video) -> None: ...
    async def list_for_project(self, project_id: uuid.UUID, params: PageParams) -> Page[Video]: ...


class SeoMetadataRepository(Protocol):
    async def get_for_video(self, video_id: uuid.UUID) -> SeoMetadata | None: ...
    async def add(self, seo_metadata: SeoMetadata) -> None: ...
    async def update(self, seo_metadata: SeoMetadata) -> None: ...
