from __future__ import annotations

import uuid
from typing import Protocol

from ytforge.domain.entities import Voiceover, VoiceProfile


class VoiceProfileRepository(Protocol):
    async def get_by_id(self, voice_profile_id: uuid.UUID) -> VoiceProfile | None: ...
    async def add(self, voice_profile: VoiceProfile) -> None: ...
    async def update(self, voice_profile: VoiceProfile) -> None: ...
    async def list_for_channel(self, channel_id: uuid.UUID) -> list[VoiceProfile]: ...


class VoiceoverRepository(Protocol):
    async def add(self, voiceover: Voiceover) -> None: ...
    async def list_for_project(self, project_id: uuid.UUID) -> list[Voiceover]: ...
